pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Stonecutter'
            url = 'https://maven.kikugie.dev/releases'
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'dev.kikugie.stonecutter' version '0.9.8'
}

rootProject.name = 'iron-oak'

include('common')
include('fabric')

stonecutter {
    centralScript = 'build.gradle'
    kotlinController = false

    create(rootProject) {
        branch('common') { versions('1.21.1', '26.3') }
        branch('fabric') { versions('1.21.1', '26.3') }
        vcsVersion = '26.3'
    }
}
